# APIs for data retrieval

An Application Programming Interface, commonly known as API, is a set of protocols, routines, and tools for building software applications. APIs allow different software systems to communicate with each other and exchange data in a standardized and efficient way.

APIs for retrieving data enable developers to access and extract information from various sources such as databases, web services, or applications. These APIs often provide a structured and consistent way of accessing data, making it easier for developers to consume and use the data in their applications.

APIs for retrieving data can be used for a variety of purposes, such as gathering information for business intelligence, analyzing user behavior, or integrating data from different sources into a single application. These APIs often use standardized data formats, such as JSON or XML, to ensure compatibility and interoperability between different systems.

As the amount of data available online continues to grow, APIs for retrieving data have become an essential tool for developers to access and analyze this data. By leveraging these APIs, developers can quickly and easily retrieve the data they need, without having to manually extract and process it themselves.

### API types
There are several types of APIs available, but two of the most commonly used types are REST API and HTTP API.

- REST API (Representational State Transfer API):
REST stands for Representational State Transfer, and it's a set of architectural principles for building web services. A REST API is a type of web service that follows the REST architecture principles. REST APIs use HTTP methods (GET, POST, PUT, DELETE, etc.) to access and manipulate resources, which are identified by URIs (Uniform Resource Identifiers). REST APIs typically return data in JSON or XML format and are widely used for building web and mobile applications.


- HTTP API (Hypertext Transfer Protocol API):
HTTP stands for Hypertext Transfer Protocol, which is the protocol used for transferring data over the World Wide Web. An HTTP API is a type of web service that uses HTTP methods to access and manipulate resources. An HTTP API can be RESTful, but it doesn't have to be. HTTP APIs are often used for simple operations like CRUD (Create, Read, Update, Delete) on resources and return data in JSON or XML format.


Other types of APIs include SOAP (Simple Object Access Protocol), GraphQL, and WebSockets. SOAP is an older protocol used for building web services, while GraphQL is a newer API technology that allows clients to specify the data they need and receive it in a single request. WebSockets are used for real-time, two-way communication between a client and a server.

### python and APIs

Python is a popular programming language that provides powerful tools for interacting with APIs. Here are the steps to interact with APIs using Python:

1. Import the necessary libraries: Python has several libraries that make it easy to interact with APIs, including requests, json, and urllib. Before making any API requests, you need to import the appropriate libraries.

2. Find the API endpoint: The endpoint is the URL that you will use to send your API requests. It's essential to understand the API documentation to find the correct endpoint for the specific data you want to retrieve.

3. Send a request: Once you have the endpoint, you can use Python's requests library to send an HTTP request to the API endpoint. The requests library has several methods for sending different types of HTTP requests, including GET, POST, PUT, DELETE, and more.

4. Parse the response: The API response will typically be in JSON format. Python's json library can be used to parse the JSON data and convert it into a Python dictionary that you can easily work with in your code.

5. Extract the data: Once you have the API response in a Python dictionary, you can extract the data you need and use it in your application.

Python's ease of use and powerful libraries make it an excellent language for interacting with APIs. With just a few lines of code, you can send requests to APIs, parse the response data, and extract the information you need to build powerful applications.

### Using the request package

To do this, we need to know how to send requests first. We will use an amazing package called [`requests`](http://docs.python-requests.org/en/master/). If you do not have it installed, please install it using e.g. `poetry add` (in your command prompt or terminal):


```$ poetry add requests``` or ```$ pip install requests```

In [1]:
import requests # library for making HTTP requests
import pandas as pd # library for data analysis
import datetime as dt # library for handling date and time objects

###### open DMI weather data 

Go to the [documentation](https://opendatadocs.dmi.govcloud.dk/en/DMIOpenData)

Using weather as an example, we should first know what is the request URL (where the request goes to), with what parameters(e.g., API key and stationID). In our case, we know that our API key and the stationId to query so we can do the following.

You will have to create a user and retrieve an API key for the API you want to use [how to](https://opendatadocs.dmi.govcloud.dk/Authentication)

I have saved my API key in an file ```.env```
    
    api_key = your_api_key 

Specifically we will look at [Meteorological Observation](https://opendatadocs.dmi.govcloud.dk/en/APIs/Meteorological_Observation_API)

In [4]:
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.environ['api_key']

In [ ]:
# Alternative: Read the keys and tokens into a dictionary
# my_dict = {}

# with open("./.env", "r") as f:
#     for line in f:
#         key,val = line.split('=')
#         my_dict[key.strip()] = val.strip()
        
# api_key = my_dict['api_key']

In [5]:
stationId = '06074' # list of stationId: https://confluence.govcloud.dk/pages/viewpage.action?pageId=41717704

In [6]:
DMI_URL = 'https://dmigw.govcloud.dk/v2/metObs/collections/station/items'
r = requests.get(DMI_URL, params={'api-key': api_key, "stationId": stationId}) # Issues a HTTP GET request
r.url # `requests` help us encode the URL in the correct format

'https://dmigw.govcloud.dk/v2/metObs/collections/station/items?api-key=98ec120f-22ae-4c65-bee5-c7979ce58fe2&stationId=06074'

In [7]:
r.status_code # 200 means success

200

In [8]:
station = r.json()
station

{'type': 'FeatureCollection',
 'features': [{'geometry': {'coordinates': [10.1703, 56.1945],
    'type': 'Point'},
   'id': '1534ad6f-44ca-722c-02de-222ed7c5873b',
   'type': 'Feature',
   'properties': {'barometerHeight': None,
    'country': 'DNK',
    'created': '2025-01-28T12:09:36Z',
    'name': 'Kirstinesminde Flyveplads',
    'operationFrom': '1976-06-14T00:00:00Z',
    'operationTo': None,
    'owner': 'DMI',
    'parameterId': ['cloud_cover',
     'cloud_height',
     'humidity',
     'humidity_past1h',
     'precip_dur_past10min',
     'precip_dur_past1h',
     'precip_past10min',
     'precip_past1h',
     'pressure',
     'pressure_at_sea',
     'temp_dew',
     'temp_dry',
     'temp_max_past12h',
     'temp_max_past1h',
     'temp_mean_past1h',
     'temp_min_past12h',
     'temp_min_past1h',
     'visib_mean_last10min',
     'visibility',
     'weather',
     'wind_dir',
     'wind_dir_past1h',
     'wind_gust_always_past1h',
     'wind_max',
     'wind_max_per10min_past1h',
     'wind_min',
     'wind_min_past1h',
     'wind_speed',
     'wind_speed_past1h'],
    'regionId': '6',
    'stationHeight': None,
    'stationId': '06074',
    'status': 'Active',
    'type': 'Synop',
    'updated': None,
    'validFrom': '1976-06-14T00:00:00Z',
    'validTo': '1987-09-21T00:00:00Z',
    'wmoCountryCode': '6080',
    'wmoStationId': '06074'}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'ab5b5587-1c0e-0752-e81c-08a36b6878d6',
   'type': 'Feature',
   'properties': {'barometerHeight': None,
    'country': 'DNK',
    'created': '2025-01-28T12:09:36Z',
    'name': 'Århus Syd',
    'operationFrom': '1976-06-14T00:00:00Z',
    'operationTo': None,
    'owner': 'DMI',
    'parameterId': ['cloud_cover',
     'cloud_height',
     'humidity',
     'humidity_past1h',
     'precip_dur_past10min',
     'precip_dur_past1h',
     'precip_past10min',
     'precip_past1h',
     'pressure',
     'pressure_at_sea',
     'temp_dew',
     'temp_dry',
     'temp_max_past12h',
     'temp_max_past1h',
     'temp_mean_past1h',
     'temp_min_past12h',
     'temp_min_past1h',
     'visib_mean_last10min',
     'visibility',
     'weather',
     'wind_dir',
     'wind_dir_past1h',
     'wind_gust_always_past1h',
     'wind_max',
     'wind_max_per10min_past1h',
     'wind_min',
     'wind_min_past1h',
     'wind_speed',
     'wind_speed_past1h'],
    'regionId': '6',
    'stationHeight': 53.82,
    'stationId': '06074',
    'status': 'Active',
    'type': 'Synop',
    'updated': None,
    'validFrom': '1987-09-21T00:00:00Z',
    'validTo': '2019-01-15T13:34:47Z',
    'wmoCountryCode': '6080',
    'wmoStationId': '06074'}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'e07ec26d-b226-9305-13dc-605e67cf0bc1',
   'type': 'Feature',
   'properties': {'barometerHeight': 55.47,
    'country': 'DNK',
    'created': '2025-01-28T12:09:36Z',
    'name': 'Århus Syd',
    'operationFrom': '1976-06-14T00:00:00Z',
    'operationTo': None,
    'owner': 'DMI',
    'parameterId': ['cloud_cover',
     'cloud_height',
     'humidity',
     'humidity_past1h',
     'precip_dur_past10min',
     'precip_dur_past1h',
     'precip_past10min',
     'precip_past1h',
     'pressure',
     'pressure_at_sea',
     'temp_dew',
     'temp_dry',
     'temp_max_past12h',
     'temp_max_past1h',
     'temp_mean_past1h',
     'temp_min_past12h',
     'temp_min_past1h',
     'visib_mean_last10min',
     'visibility',
     'weather',
     'wind_dir',
     'wind_dir_past1h',
     'wind_gust_always_past1h',
     'wind_max',
     'wind_max_per10min_past1h',
     'wind_min',
     'wind_min_past1h',
     'wind_speed',
     'wind_speed_past1h'],
    'regionId': '6',
    'stationHeight': 53.82,
    'stationId': '06074',
    'status': 'Active',
    'type': 'Synop',
    'updated': None,
    'validFrom': '2019-01-15T13:34:47Z',
    'validTo': None,
    'wmoCountryCode': '6080',
    'wmoStationId': '06074'}}],
 'timeStamp': '2025-03-17T07:41:40Z',
 'numberReturned': 3,
 'links': [{'href': 'https://dmigw.govcloud.dk/v2/metObs/collections/station/items?api-key=98ec120f-22ae-4c65-bee5-c7979ce58fe2&stationId=06074',
   'rel': 'self',
   'type': 'application/geo+json',
   'title': 'This document'},
  {'href': 'https://dmigw.govcloud.dk/v2/metObs/collections/station/items?api-key=98ec120f-22ae-4c65-bee5-c7979ce58fe2&stationId=06074&offset=3',
   'rel': 'next',
   'type': 'application/geo+json',
   'title': 'Next set of results'}]}

In [9]:
DMI_URL = 'https://dmigw.govcloud.dk/v2/metObs/collections/observation/items'
r = requests.get(DMI_URL, params={'api-key': api_key, "stationId": '06074', 'period': 'latest-day', 'parameterId': 'temp_dry'}) # Issues a HTTP GET request
print(r)

<Response [200]>

In [10]:
dmi = r.json()  # Extract JSON data
dmi  # Print the keys of the JSON dictionary

{'type': 'FeatureCollection',
 'features': [{'geometry': {'coordinates': [10.1353, 56.0803],
    'type': 'Point'},
   'id': 'ffed29a4-5186-85ec-3566-928cd58a3a7c',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T07:38:44.888707Z',
    'observed': '2025-03-17T07:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': 0.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'd8110035-1ac5-e040-f18b-14b39c6de5bd',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T07:28:48.151130Z',
    'observed': '2025-03-17T07:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': 0.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'd7350a64-9044-a9c6-ffcc-8e7e67fe2a42',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T07:18:41.879446Z',
    'observed': '2025-03-17T07:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': 0.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'fd3df342-ab0f-613a-74db-cf4b1207b208',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T07:08:41.628765Z',
    'observed': '2025-03-17T07:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -0.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '70bf3515-4830-1cf4-4480-1a1a52b156b4',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T06:58:43.380855Z',
    'observed': '2025-03-17T07:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.7}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'ec13d540-727a-17b7-9f3d-a273e75d6701',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T06:48:43.136996Z',
    'observed': '2025-03-17T06:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.1}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '05162cff-7d6e-5f1d-48bc-3c763d734091',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T06:38:45.432787Z',
    'observed': '2025-03-17T06:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.7}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '0e20708e-33d8-5d06-3474-5d65e55efea2',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T06:28:42.629701Z',
    'observed': '2025-03-17T06:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -4.9}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'cdb2decd-ea94-5b9c-3c0a-4e009e32b40e',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T06:18:44.933854Z',
    'observed': '2025-03-17T06:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.1}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'fae7704f-03af-335d-09ee-102d48e0a07e',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T06:08:43.134609Z',
    'observed': '2025-03-17T06:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '702935a4-720e-8cdd-ff4a-ea4e4c6e0b37',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T05:58:46.892235Z',
    'observed': '2025-03-17T06:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '8c7fdb83-c0d1-2594-a906-c93b01120ae0',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T05:48:48.649940Z',
    'observed': '2025-03-17T05:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '4a268e64-961a-f776-8316-981e71512e76',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T05:38:42.874410Z',
    'observed': '2025-03-17T05:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.4}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '330b6b97-5750-c20b-8ae7-ca6c9c44002d',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T05:28:45.124306Z',
    'observed': '2025-03-17T05:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -4.8}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '841f8ddb-880a-fdc6-a12a-bd4f3cdd3ade',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T05:18:42.830047Z',
    'observed': '2025-03-17T05:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '820ea019-8d9e-3288-5e98-9f465e9edce7',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T05:08:46.576070Z',
    'observed': '2025-03-17T05:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -5.4}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '01f03639-82bc-d571-8e19-6f24437304a5',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T04:58:50.340713Z',
    'observed': '2025-03-17T05:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -4.8}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '998e1b30-1144-d36d-4378-fe99b11820fc',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T04:48:43.065506Z',
    'observed': '2025-03-17T04:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -4.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '0a28096e-f244-864d-4f68-e96798261a72',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T04:38:45.851173Z',
    'observed': '2025-03-17T04:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -4.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'e01af66c-ed85-8b92-c5ae-a033a9d73a60',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T04:28:45.578923Z',
    'observed': '2025-03-17T04:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.9}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '6f70312e-dc74-7413-a38c-74049b4bdaca',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T04:18:44.834831Z',
    'observed': '2025-03-17T04:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -4.1}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'be430910-9105-f097-a3f0-a510e980fcb0',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T04:08:42.580478Z',
    'observed': '2025-03-17T04:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.7}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '6d02ac89-868c-2ee4-1ae9-c61090cf365c',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T03:58:48.337439Z',
    'observed': '2025-03-17T04:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'bcbe702f-3652-85ef-7880-6a8080aae52b',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T03:48:45.634754Z',
    'observed': '2025-03-17T03:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'c851496e-a865-d235-2a5d-d0f959880bce',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T03:38:45.806209Z',
    'observed': '2025-03-17T03:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.8}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '316b8f73-5a4f-f5f9-214d-03b527c94865',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T03:28:43.554603Z',
    'observed': '2025-03-17T03:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '35570a47-cb27-9f62-d1ca-818abf5aaad0',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T03:18:46.337516Z',
    'observed': '2025-03-17T03:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.4}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '7d64e401-8f5b-9d86-911b-0b4a1bdb4374',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T03:08:43.536082Z',
    'observed': '2025-03-17T03:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.7}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '37235f26-c799-ef14-3502-60c7714ad38b',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T02:58:49.294898Z',
    'observed': '2025-03-17T03:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.7}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'ac0d82a0-ef29-a8c1-d14f-c1e9b237b474',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T02:48:43.038468Z',
    'observed': '2025-03-17T02:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '0710cedd-f9d1-a15d-e425-d683c518bc22',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T02:38:42.299818Z',
    'observed': '2025-03-17T02:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.4}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'ff99daca-8702-3fe9-136a-aa5a21e5e0ba',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T02:28:43.499809Z',
    'observed': '2025-03-17T02:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -3.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'b03a96d7-3834-81e6-d94d-ce75b0cbf6bc',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T02:18:51.283235Z',
    'observed': '2025-03-17T02:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.8}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '2ed69a97-4252-a05e-14f9-25d40bdfbd05',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T02:08:45.029297Z',
    'observed': '2025-03-17T02:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.9}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '00578680-8cfe-f89a-46ba-f0430624bf2b',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T01:58:45.734693Z',
    'observed': '2025-03-17T02:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '39ea853c-1b46-0b0e-7ffc-1fad62955cf4',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T01:48:48.533963Z',
    'observed': '2025-03-17T01:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '04d2477b-b3d0-78ff-93a0-506f1c840406',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T01:38:45.334057Z',
    'observed': '2025-03-17T01:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.0}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '25b28bb1-d3dd-d15c-6d65-cd247d0970be',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T01:28:44.990623Z',
    'observed': '2025-03-17T01:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.0}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '9d8fafe8-bb73-bf65-c939-f3b39838745c',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T01:18:49.332802Z',
    'observed': '2025-03-17T01:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.9}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '3e363c96-c6a0-f7c9-d94e-748e735d5f38',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T01:08:44.033120Z',
    'observed': '2025-03-17T01:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.9}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '5daf6688-62ed-c636-bcf8-93661593c75d',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T00:58:42.746162Z',
    'observed': '2025-03-17T01:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'ae79df70-e8b9-aea0-6099-fecd9d9ee52e',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T00:48:46.532319Z',
    'observed': '2025-03-17T00:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '5d5c9ec3-b50d-fc1f-95b0-2055890c2521',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T00:38:46.329516Z',
    'observed': '2025-03-17T00:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '1d5ccbd4-58db-d95e-9048-83da01de375b',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T00:28:50.503787Z',
    'observed': '2025-03-17T00:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -2.1}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'f833e45d-b3c7-83c5-5444-993ea3e1ba0f',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T00:18:47.233223Z',
    'observed': '2025-03-17T00:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.7}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '60cc440a-df9b-93ac-b2c7-cbabed280287',
   'type': 'Feature',
   'properties': {'created': '2025-03-17T00:08:44.543049Z',
    'observed': '2025-03-17T00:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '773335ff-1181-281d-4320-a3c2e4c0ed86',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T23:59:01.733556Z',
    'observed': '2025-03-17T00:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '60bebd68-d71a-f5b6-4972-53144ee4e7ee',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T23:48:43.945355Z',
    'observed': '2025-03-16T23:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'a3162eea-3c66-e62f-a727-f61c278f2cfb',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T23:38:43.599176Z',
    'observed': '2025-03-16T23:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.0}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'e2d39e0c-7ddd-7944-7a2d-3da167500c91',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T23:28:46.430352Z',
    'observed': '2025-03-16T23:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.1}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '262bd469-5268-026b-cc21-ec2fd8a55cf5',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T23:18:41.113674Z',
    'observed': '2025-03-16T23:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'd20453b0-c4b3-0c9a-bddc-94317e927353',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T23:08:41.845937Z',
    'observed': '2025-03-16T23:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.8}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'f8142fab-56b1-d7f3-5d81-923e3d5ae753',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T22:58:47.526681Z',
    'observed': '2025-03-16T23:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '686e677b-6408-f3d0-d073-bfd33042b825',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T22:48:43.232112Z',
    'observed': '2025-03-16T22:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '05e9f281-3887-ddaa-9c15-e9aabd25b935',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T22:38:42.451517Z',
    'observed': '2025-03-16T22:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -0.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '7a804eb2-379c-d8a3-73af-53135006de49',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T22:28:42.229631Z',
    'observed': '2025-03-16T22:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.5}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '0dc07d9e-41d6-6888-1460-0e8861322316',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T22:18:48.419683Z',
    'observed': '2025-03-16T22:20:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -1.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '49fa1fe8-64fb-7cc4-6e69-2fad72125642',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T22:08:45.133894Z',
    'observed': '2025-03-16T22:10:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -0.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'ed785bfc-34fa-c4e9-2d9d-7358a81cf422',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T21:58:43.352618Z',
    'observed': '2025-03-16T22:00:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': -0.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': 'e4c632a3-3b6f-f3c1-190a-ae27b1982a02',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T21:48:42.128830Z',
    'observed': '2025-03-16T21:50:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': 0.3}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '85fb900d-3b15-6188-4df2-ca6c85ec0c2a',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T21:38:41.869030Z',
    'observed': '2025-03-16T21:40:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': 1.2}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '78a29cc2-d5fc-0fef-421e-8b8d5f276e27',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T21:28:45.114156Z',
    'observed': '2025-03-16T21:30:00Z',
    'parameterId': 'temp_dry',
    'stationId': '06074',
    'value': 1.6}},
  {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
   'id': '78f88cd9-1d4e-4b7c-6596-9c9e4496c622',
   'type': 'Feature',
   'properties': {'created': '2025-03-16T21:18:41.355110Z',
    'observed': '2025-03-16T21:20:00Z',

JSON object will be converted into a `dict` type, which is the data structure in Python holding key value pairs. To access certain values, we just access them like a `dict`.

In [11]:
dmi['features']

[{'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'ffed29a4-5186-85ec-3566-928cd58a3a7c',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T07:38:44.888707Z',
   'observed': '2025-03-17T07:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 0.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'd8110035-1ac5-e040-f18b-14b39c6de5bd',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T07:28:48.151130Z',
   'observed': '2025-03-17T07:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 0.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'd7350a64-9044-a9c6-ffcc-8e7e67fe2a42',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T07:18:41.879446Z',
   'observed': '2025-03-17T07:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 0.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'fd3df342-ab0f-613a-74db-cf4b1207b208',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T07:08:41.628765Z',
   'observed': '2025-03-17T07:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -0.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '70bf3515-4830-1cf4-4480-1a1a52b156b4',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T06:58:43.380855Z',
   'observed': '2025-03-17T07:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'ec13d540-727a-17b7-9f3d-a273e75d6701',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T06:48:43.136996Z',
   'observed': '2025-03-17T06:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.1}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '05162cff-7d6e-5f1d-48bc-3c763d734091',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T06:38:45.432787Z',
   'observed': '2025-03-17T06:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '0e20708e-33d8-5d06-3474-5d65e55efea2',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T06:28:42.629701Z',
   'observed': '2025-03-17T06:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -4.9}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'cdb2decd-ea94-5b9c-3c0a-4e009e32b40e',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T06:18:44.933854Z',
   'observed': '2025-03-17T06:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.1}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'fae7704f-03af-335d-09ee-102d48e0a07e',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T06:08:43.134609Z',
   'observed': '2025-03-17T06:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '702935a4-720e-8cdd-ff4a-ea4e4c6e0b37',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T05:58:46.892235Z',
   'observed': '2025-03-17T06:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '8c7fdb83-c0d1-2594-a906-c93b01120ae0',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T05:48:48.649940Z',
   'observed': '2025-03-17T05:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '4a268e64-961a-f776-8316-981e71512e76',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T05:38:42.874410Z',
   'observed': '2025-03-17T05:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.4}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '330b6b97-5750-c20b-8ae7-ca6c9c44002d',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T05:28:45.124306Z',
   'observed': '2025-03-17T05:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -4.8}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '841f8ddb-880a-fdc6-a12a-bd4f3cdd3ade',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T05:18:42.830047Z',
   'observed': '2025-03-17T05:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '820ea019-8d9e-3288-5e98-9f465e9edce7',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T05:08:46.576070Z',
   'observed': '2025-03-17T05:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -5.4}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '01f03639-82bc-d571-8e19-6f24437304a5',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T04:58:50.340713Z',
   'observed': '2025-03-17T05:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -4.8}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '998e1b30-1144-d36d-4378-fe99b11820fc',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T04:48:43.065506Z',
   'observed': '2025-03-17T04:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -4.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '0a28096e-f244-864d-4f68-e96798261a72',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T04:38:45.851173Z',
   'observed': '2025-03-17T04:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -4.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'e01af66c-ed85-8b92-c5ae-a033a9d73a60',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T04:28:45.578923Z',
   'observed': '2025-03-17T04:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.9}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '6f70312e-dc74-7413-a38c-74049b4bdaca',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T04:18:44.834831Z',
   'observed': '2025-03-17T04:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -4.1}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'be430910-9105-f097-a3f0-a510e980fcb0',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T04:08:42.580478Z',
   'observed': '2025-03-17T04:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '6d02ac89-868c-2ee4-1ae9-c61090cf365c',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T03:58:48.337439Z',
   'observed': '2025-03-17T04:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'bcbe702f-3652-85ef-7880-6a8080aae52b',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T03:48:45.634754Z',
   'observed': '2025-03-17T03:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'c851496e-a865-d235-2a5d-d0f959880bce',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T03:38:45.806209Z',
   'observed': '2025-03-17T03:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.8}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '316b8f73-5a4f-f5f9-214d-03b527c94865',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T03:28:43.554603Z',
   'observed': '2025-03-17T03:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '35570a47-cb27-9f62-d1ca-818abf5aaad0',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T03:18:46.337516Z',
   'observed': '2025-03-17T03:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.4}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '7d64e401-8f5b-9d86-911b-0b4a1bdb4374',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T03:08:43.536082Z',
   'observed': '2025-03-17T03:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '37235f26-c799-ef14-3502-60c7714ad38b',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T02:58:49.294898Z',
   'observed': '2025-03-17T03:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'ac0d82a0-ef29-a8c1-d14f-c1e9b237b474',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T02:48:43.038468Z',
   'observed': '2025-03-17T02:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '0710cedd-f9d1-a15d-e425-d683c518bc22',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T02:38:42.299818Z',
   'observed': '2025-03-17T02:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.4}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'ff99daca-8702-3fe9-136a-aa5a21e5e0ba',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T02:28:43.499809Z',
   'observed': '2025-03-17T02:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -3.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'b03a96d7-3834-81e6-d94d-ce75b0cbf6bc',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T02:18:51.283235Z',
   'observed': '2025-03-17T02:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.8}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '2ed69a97-4252-a05e-14f9-25d40bdfbd05',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T02:08:45.029297Z',
   'observed': '2025-03-17T02:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.9}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '00578680-8cfe-f89a-46ba-f0430624bf2b',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T01:58:45.734693Z',
   'observed': '2025-03-17T02:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '39ea853c-1b46-0b0e-7ffc-1fad62955cf4',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T01:48:48.533963Z',
   'observed': '2025-03-17T01:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '04d2477b-b3d0-78ff-93a0-506f1c840406',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T01:38:45.334057Z',
   'observed': '2025-03-17T01:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.0}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '25b28bb1-d3dd-d15c-6d65-cd247d0970be',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T01:28:44.990623Z',
   'observed': '2025-03-17T01:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.0}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '9d8fafe8-bb73-bf65-c939-f3b39838745c',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T01:18:49.332802Z',
   'observed': '2025-03-17T01:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.9}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '3e363c96-c6a0-f7c9-d94e-748e735d5f38',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T01:08:44.033120Z',
   'observed': '2025-03-17T01:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.9}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '5daf6688-62ed-c636-bcf8-93661593c75d',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T00:58:42.746162Z',
   'observed': '2025-03-17T01:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'ae79df70-e8b9-aea0-6099-fecd9d9ee52e',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T00:48:46.532319Z',
   'observed': '2025-03-17T00:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '5d5c9ec3-b50d-fc1f-95b0-2055890c2521',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T00:38:46.329516Z',
   'observed': '2025-03-17T00:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '1d5ccbd4-58db-d95e-9048-83da01de375b',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T00:28:50.503787Z',
   'observed': '2025-03-17T00:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -2.1}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'f833e45d-b3c7-83c5-5444-993ea3e1ba0f',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T00:18:47.233223Z',
   'observed': '2025-03-17T00:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '60cc440a-df9b-93ac-b2c7-cbabed280287',
  'type': 'Feature',
  'properties': {'created': '2025-03-17T00:08:44.543049Z',
   'observed': '2025-03-17T00:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '773335ff-1181-281d-4320-a3c2e4c0ed86',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T23:59:01.733556Z',
   'observed': '2025-03-17T00:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '60bebd68-d71a-f5b6-4972-53144ee4e7ee',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T23:48:43.945355Z',
   'observed': '2025-03-16T23:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'a3162eea-3c66-e62f-a727-f61c278f2cfb',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T23:38:43.599176Z',
   'observed': '2025-03-16T23:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.0}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'e2d39e0c-7ddd-7944-7a2d-3da167500c91',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T23:28:46.430352Z',
   'observed': '2025-03-16T23:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.1}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '262bd469-5268-026b-cc21-ec2fd8a55cf5',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T23:18:41.113674Z',
   'observed': '2025-03-16T23:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'd20453b0-c4b3-0c9a-bddc-94317e927353',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T23:08:41.845937Z',
   'observed': '2025-03-16T23:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.8}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'f8142fab-56b1-d7f3-5d81-923e3d5ae753',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T22:58:47.526681Z',
   'observed': '2025-03-16T23:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '686e677b-6408-f3d0-d073-bfd33042b825',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T22:48:43.232112Z',
   'observed': '2025-03-16T22:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '05e9f281-3887-ddaa-9c15-e9aabd25b935',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T22:38:42.451517Z',
   'observed': '2025-03-16T22:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -0.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '7a804eb2-379c-d8a3-73af-53135006de49',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T22:28:42.229631Z',
   'observed': '2025-03-16T22:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.5}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '0dc07d9e-41d6-6888-1460-0e8861322316',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T22:18:48.419683Z',
   'observed': '2025-03-16T22:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -1.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '49fa1fe8-64fb-7cc4-6e69-2fad72125642',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T22:08:45.133894Z',
   'observed': '2025-03-16T22:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -0.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'ed785bfc-34fa-c4e9-2d9d-7358a81cf422',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T21:58:43.352618Z',
   'observed': '2025-03-16T22:00:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': -0.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': 'e4c632a3-3b6f-f3c1-190a-ae27b1982a02',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T21:48:42.128830Z',
   'observed': '2025-03-16T21:50:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 0.3}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '85fb900d-3b15-6188-4df2-ca6c85ec0c2a',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T21:38:41.869030Z',
   'observed': '2025-03-16T21:40:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 1.2}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '78a29cc2-d5fc-0fef-421e-8b8d5f276e27',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T21:28:45.114156Z',
   'observed': '2025-03-16T21:30:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 1.6}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '78f88cd9-1d4e-4b7c-6596-9c9e4496c622',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T21:18:41.355110Z',
   'observed': '2025-03-16T21:20:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 1.8}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '9284a2c9-2cd1-5686-3ea1-bd79dcf2153d',
  'type': 'Feature',
  'properties': {'created': '2025-03-16T21:08:44.578782Z',
   'observed': '2025-03-16T21:10:00Z',
   'parameterId': 'temp_dry',
   'stationId': '06074',
   'value': 1.7}},
 {'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
  'id': '519793cc-6ed5-bc17-c664-eb50b42627ac',
  'type': 'Feature',

In [13]:
dmi['features'][0]

{'geometry': {'coordinates': [10.1353, 56.0803], 'type': 'Point'},
 'id': 'ffed29a4-5186-85ec-3566-928cd58a3a7c',
 'type': 'Feature',
 'properties': {'created': '2025-03-17T07:38:44.888707Z',
  'observed': '2025-03-17T07:40:00Z',
  'parameterId': 'temp_dry',
  'stationId': '06074',
  'value': 0.6}}

In [14]:
dmi['features'][0]['properties']

{'created': '2025-03-17T07:38:44.888707Z',
 'observed': '2025-03-17T07:40:00Z',
 'parameterId': 'temp_dry',
 'stationId': '06074',
 'value': 0.6}

In [15]:
dmi['features'][0]['properties']['value']

0.6

In [16]:
for feature in dmi['features']:
    for key, value in feature['properties'].items():
         print(key, value)

created 2025-03-17T07:38:44.888707Z
observed 2025-03-17T07:40:00Z
parameterId temp_dry
stationId 06074
value 0.6
created 2025-03-17T07:28:48.151130Z
observed 2025-03-17T07:30:00Z
parameterId temp_dry
stationId 06074
value 0.5
created 2025-03-17T07:18:41.879446Z
observed 2025-03-17T07:20:00Z
parameterId temp_dry
stationId 06074
value 0.2
created 2025-03-17T07:08:41.628765Z
observed 2025-03-17T07:10:00Z
parameterId temp_dry
stationId 06074
value -0.2
created 2025-03-17T06:58:43.380855Z
observed 2025-03-17T07:00:00Z
parameterId temp_dry
stationId 06074
value -1.7
created 2025-03-17T06:48:43.136996Z
observed 2025-03-17T06:50:00Z
parameterId temp_dry
stationId 06074
value -2.1
created 2025-03-17T06:38:45.432787Z
observed 2025-03-17T06:40:00Z
parameterId temp_dry
stationId 06074
value -3.7
created 2025-03-17T06:28:42.629701Z
observed 2025-03-17T06:30:00Z
parameterId temp_dry
stationId 06074
value -4.9
created 2025-03-17T06:18:44.933854Z
observed 2025-03-17T06:20:00Z
parameterId temp_dry
stationId 06074
value -5.1
created 2025-03-17T06:08:43.134609Z
observed 2025-03-17T06:10:00Z
parameterId temp_dry
stationId 06074
value -5.3
created 2025-03-17T05:58:46.892235Z
observed 2025-03-17T06:00:00Z
parameterId temp_dry
stationId 06074
value -5.5
created 2025-03-17T05:48:48.649940Z
observed 2025-03-17T05:50:00Z
parameterId temp_dry
stationId 06074
value -5.5
created 2025-03-17T05:38:42.874410Z
observed 2025-03-17T05:40:00Z
parameterId temp_dry
stationId 06074
value -5.4
created 2025-03-17T05:28:45.124306Z
observed 2025-03-17T05:30:00Z
parameterId temp_dry
stationId 06074
value -4.8
created 2025-03-17T05:18:42.830047Z
observed 2025-03-17T05:20:00Z
parameterId temp_dry
stationId 06074
value -5.3
created 2025-03-17T05:08:46.576070Z
observed 2025-03-17T05:10:00Z
parameterId temp_dry
stationId 06074
value -5.4
created 2025-03-17T04:58:50.340713Z
observed 2025-03-17T05:00:00Z
parameterId temp_dry
stationId 06074
value -4.8
created 2025-03-17T04:48:43.065506Z
observed 2025-03-17T04:50:00Z
parameterId temp_dry
stationId 06074
value -4.5
created 2025-03-17T04:38:45.851173Z
observed 2025-03-17T04:40:00Z
parameterId temp_dry
stationId 06074
value -4.2
created 2025-03-17T04:28:45.578923Z
observed 2025-03-17T04:30:00Z
parameterId temp_dry
stationId 06074
value -3.9
created 2025-03-17T04:18:44.834831Z
observed 2025-03-17T04:20:00Z
parameterId temp_dry
stationId 06074
value -4.1
created 2025-03-17T04:08:42.580478Z
observed 2025-03-17T04:10:00Z
parameterId temp_dry
stationId 06074
value -3.7
created 2025-03-17T03:58:48.337439Z
observed 2025-03-17T04:00:00Z
parameterId temp_dry
stationId 06074
value -3.3
created 2025-03-17T03:48:45.634754Z
observed 2025-03-17T03:50:00Z
parameterId temp_dry
stationId 06074
value -3.3
created 2025-03-17T03:38:45.806209Z
observed 2025-03-17T03:40:00Z
parameterId temp_dry
stationId 06074
value -3.8
created 2025-03-17T03:28:43.554603Z
observed 2025-03-17T03:30:00Z
parameterId temp_dry
stationId 06074
value -3.6
created 2025-03-17T03:18:46.337516Z
observed 2025-03-17T03:20:00Z
parameterId temp_dry
stationId 06074
value -3.4
created 2025-03-17T03:08:43.536082Z
observed 2025-03-17T03:10:00Z
parameterId temp_dry
stationId 06074
value -3.7
created 2025-03-17T02:58:49.294898Z
observed 2025-03-17T03:00:00Z
parameterId temp_dry
stationId 06074
value -3.7
created 2025-03-17T02:48:43.038468Z
observed 2025-03-17T02:50:00Z
parameterId temp_dry
stationId 06074
value -3.5
created 2025-03-17T02:38:42.299818Z
observed 2025-03-17T02:40:00Z
parameterId temp_dry
stationId 06074
value -3.4
created 2025-03-17T02:28:43.499809Z
observed 2025-03-17T02:30:00Z
parameterId temp_dry
stationId 06074
value -3.2
created 2025-03-17T02:18:51.283235Z
observed 2025-03-17T02:20:00Z
parameterId temp_dry
stationId 06074
value -2.8
created 2025-03-17T02:08:45.029297Z
observed 2025-03-17T02:10:00Z
parameterId temp_dry
stationId 06074
value -2.9
created 2025-03-17T01:58:45.734693Z
observed 2025-03-17T02:00:00Z
parameterId temp_dry
stationId 06074
value -2.6
created 2025-03-17T01:48:48.533963Z
observed 2025-03-17T01:50:00Z
parameterId temp_dry
stationId 06074
value -2.2
created 2025-03-17T01:38:45.334057Z
observed 2025-03-17T01:40:00Z
parameterId temp_dry
stationId 06074
value -2.0
created 2025-03-17T01:28:44.990623Z
observed 2025-03-17T01:30:00Z
parameterId temp_dry
stationId 06074
value -2.0
created 2025-03-17T01:18:49.332802Z
observed 2025-03-17T01:20:00Z
parameterId temp_dry
stationId 06074
value -1.9
created 2025-03-17T01:08:44.033120Z
observed 2025-03-17T01:10:00Z
parameterId temp_dry
stationId 06074
value -1.9
created 2025-03-17T00:58:42.746162Z
observed 2025-03-17T01:00:00Z
parameterId temp_dry
stationId 06074
value -2.6
created 2025-03-17T00:48:46.532319Z
observed 2025-03-17T00:50:00Z
parameterId temp_dry
stationId 06074
value -2.5
created 2025-03-17T00:38:46.329516Z
observed 2025-03-17T00:40:00Z
parameterId temp_dry
stationId 06074
value -2.3
created 2025-03-17T00:28:50.503787Z
observed 2025-03-17T00:30:00Z
parameterId temp_dry
stationId 06074
value -2.1
created 2025-03-17T00:18:47.233223Z
observed 2025-03-17T00:20:00Z
parameterId temp_dry
stationId 06074
value -1.7
created 2025-03-17T00:08:44.543049Z
observed 2025-03-17T00:10:00Z
parameterId temp_dry
stationId 06074
value -1.5
created 2025-03-16T23:59:01.733556Z
observed 2025-03-17T00:00:00Z
parameterId temp_dry
stationId 06074
value -1.3
created 2025-03-16T23:48:43.945355Z
observed 2025-03-16T23:50:00Z
parameterId temp_dry
stationId 06074
value -1.2
created 2025-03-16T23:38:43.599176Z
observed 2025-03-16T23:40:00Z
parameterId temp_dry
stationId 06074
value -1.0
created 2025-03-16T23:28:46.430352Z
observed 2025-03-16T23:30:00Z
parameterId temp_dry
stationId 06074
value -1.1
created 2025-03-16T23:18:41.113674Z
observed 2025-03-16T23:20:00Z
parameterId temp_dry
stationId 06074
value -1.6
created 2025-03-16T23:08:41.845937Z
observed 2025-03-16T23:10:00Z
parameterId temp_dry
stationId 06074
value -1.8
created 2025-03-16T22:58:47.526681Z
observed 2025-03-16T23:00:00Z
parameterId temp_dry
stationId 06074
value -1.3
created 2025-03-16T22:48:43.232112Z
observed 2025-03-16T22:50:00Z
parameterId temp_dry
stationId 06074
value -1.2
created 2025-03-16T22:38:42.451517Z
observed 2025-03-16T22:40:00Z
parameterId temp_dry
stationId 06074
value -0.6
created 2025-03-16T22:28:42.229631Z
observed 2025-03-16T22:30:00Z
parameterId temp_dry
stationId 06074
value -1.5
created 2025-03-16T22:18:48.419683Z
observed 2025-03-16T22:20:00Z
parameterId temp_dry
stationId 06074
value -1.3
created 2025-03-16T22:08:45.133894Z
observed 2025-03-16T22:10:00Z
parameterId temp_dry
stationId 06074
value -0.6
created 2025-03-16T21:58:43.352618Z
observed 2025-03-16T22:00:00Z
parameterId temp_dry
stationId 06074
value -0.6
created 2025-03-16T21:48:42.128830Z
observed 2025-03-16T21:50:00Z
parameterId temp_dry
stationId 06074
value 0.3
created 2025-03-16T21:38:41.869030Z
observed 2025-03-16T21:40:00Z
parameterId temp_dry
stationId 06074
value 1.2
created 2025-03-16T21:28:45.114156Z
observed 2025-03-16T21:30:00Z
parameterId temp_dry
stationId 06074
value 1.6
created 2025-03-16T21:18:41.355110Z
observed 2025-03-16T21:20:00Z
parameterId temp_dry
stationId 06074
value 1.8
created 2025-03-16T21:08:44.578782Z
observed 2025-03-16T21:10:00Z
parameterId temp_dry
stationId 06074
value 1.7
created 2025-03-16T20:58:44.274969Z
observed 2025-03-16T21:00:00Z
parameterId temp_dry
stationId 06074
value 1.9
created 2025-03-16T20:48:46.938717Z
observed 2025-03-16T20:50:00Z
parameterId temp_dry
stationId 06074
value 2.1
created 2025-03-16T20:38:46.167047Z
observed 2025-03-16T20:40:00Z
parameterId temp_dry
stationId 06074
value 2.1
created 2025-03-16T20:28:45.436496Z
observed 2025-03-16T20:30:00Z
parameterId temp_dry
stationId 06074
value 2.3
created 2025-03-16T20:18:42.139470Z
observed 2025-03-16T20:20:00Z
parameterId temp_dry
stationId 06074
value 2.1
created 2025-03-16T20:08:48.368817Z
observed 2025-03-16T20:10:00Z
parameterId temp_dry
stationId 06074
value 2.4
created 2025-03-16T19:58:42.599848Z
observed 2025-03-16T20:00:00Z
parameterId temp_dry
stationId 06074
value 2.5
created 2025-03-16T19:48:51.934677Z
observed 2025-03-16T19:50:00Z
parameterId temp_dry
stationId 06074
value 2.4
created 2025-03-16T19:38:46.603890Z
observed 2025-03-16T19:40:00Z
parameterId temp_dry
stationId 06074
value 2.2
created 2025-03-16T19:28:48.363131Z
observed 2025-03-16T19:30:00Z
parameterId temp_dry
stationId 06074
value 2.4
created 2025-03-16T19:18:47.134201Z
observed 2025-03-16T19:20:00Z
parameterId temp_dry
stationId 06074
value 2.3
created 2025-03-16T19:08:42.839642Z
observed 2025-03-16T19:10:00Z
parameterId temp_dry
stationId 06074
value 2.3
created 2025-03-16T18:58:48.049261Z
observed 2025-03-16T19:00:00Z
parameterId temp_dry
stationId 06074
value 2.7
created 2025-03-16T18:48:46.745027Z
observed 2025-03-16T18:50:00Z
parameterId temp_dry
stationId 06074
value 2.8
created 2025-03-16T18:38:46.974390Z
observed 2025-03-16T18:40:00Z
parameterId temp_dry
stationId 06074
value 2.8
created 2025-03-16T18:28:44.230353Z
observed 2025-03-16T18:30:00Z
parameterId temp_dry
stationId 06074
value 3.0
created 2025-03-16T18:18:43.931122Z
observed 2025-03-16T18:20:00Z
parameterId temp_dry
stationId 06074
value 3.2
created 2025-03-16T18:08:45.632009Z
observed 2025-03-16T18:10:00Z
parameterId temp_dry
stationId 06074
value 3.2
created 2025-03-16T17:58:43.234027Z
observed 2025-03-16T18:00:00Z
parameterId temp_dry
stationId 06074
value 3.7
created 2025-03-16T17:48:41.989082Z
observed 2025-03-16T17:50:00Z
parameterId temp_dry
stationId 06074
value 3.9
created 2025-03-16T17:38:43.739866Z
observed 2025-03-16T17:40:00Z
parameterId temp_dry
stationId 06074
value 4.2
created 2025-03-16T17:28:43.968525Z
observed 2025-03-16T17:30:00Z
parameterId temp_dry
stationId 06074
value 4.2
created 2025-03-16T17:18:44.698980Z
observed 2025-03-16T17:20:00Z
parameterId temp_dry
stationId 06074
value 4.4
created 2025-03-16T17:08:43.045320Z
observed 2025-03-16T17:10:00Z
parameterId temp_dry
stationId 06074
value 4.6
created 2025-03-16T16:58:42.134960Z
observed 2025-03-16T17:00:00Z
parameterId temp_dry
stationId 06074
value 4.7
created 2025-03-16T16:48:45.939377Z
observed 2025-03-16T16:50:00Z
parameterId temp_dry
stationId 06074
value 4.7
created 2025-03-16T16:38:48.637237Z
observed 2025-03-16T16:40:00Z
parameterId temp_dry
stationId 06074
value 4.9
created 2025-03-16T16:28:47.829070Z
observed 2025-03-16T16:30:00Z
parameterId temp_dry
stationId 06074
value 5.1
created 2025-03-16T16:18:41.991157Z
observed 2025-03-16T16:20:00Z
parameterId temp_dry
stationId 06074
value 5.4
created 2025-03-16T16:08:41.737808Z
observed 2025-03-16T16:10:00Z
parameterId temp_dry
stationId 06074
value 5.7
created 2025-03-16T15:58:46.492687Z
observed 2025-03-16T16:00:00Z
parameterId temp_dry
stationId 06074
value 6.1
created 2025-03-16T15:48:45.254700Z
observed 2025-03-16T15:50:00Z
parameterId temp_dry
stationId 06074
value 6.4
created 2025-03-16T15:38:48.038697Z
observed 2025-03-16T15:40:00Z
parameterId temp_dry
stationId 06074
value 6.7
created 2025-03-16T15:28:41.744843Z
observed 2025-03-16T15:30:00Z
parameterId temp_dry
stationId 06074
value 6.9
created 2025-03-16T15:18:50.030048Z
observed 2025-03-16T15:20:00Z
parameterId temp_dry
stationId 06074
value 6.9
created 2025-03-16T15:08:42.213598Z
observed 2025-03-16T15:10:00Z
parameterId temp_dry
stationId 06074
value 7.2
created 2025-03-16T14:58:41.950136Z
observed 2025-03-16T15:00:00Z
parameterId temp_dry
stationId 06074
value 7.4
created 2025-03-16T14:48:45.191989Z
observed 2025-03-16T14:50:00Z
parameterId temp_dry
stationId 06074
value 7.3
created 2025-03-16T14:38:43.454782Z
observed 2025-03-16T14:40:00Z
parameterId temp_dry
stationId 06074
value 6.9
created 2025-03-16T14:28:44.234093Z
observed 2025-03-16T14:30:00Z
parameterId temp_dry
stationId 06074
value 7.3
created 2025-03-16T14:18:46.885906Z
observed 2025-03-16T14:20:00Z
parameterId temp_dry
stationId 06074
value 7.0
created 2025-03-16T14:08:42.054029Z
observed 2025-03-16T14:10:00Z
parameterId temp_dry
stationId 06074
value 7.3
created 2025-03-16T13:58:45.803753Z
observed 2025-03-16T14:00:00Z
parameterId temp_dry
stationId 06074
value 7.8
created 2025-03-16T13:48:51.557678Z
observed 2025-03-16T13:50:00Z
parameterId temp_dry
stationId 06074
value 8.0
created 2025-03-16T13:38:42.806654Z
observed 2025-03-16T13:40:00Z
parameterId temp_dry
stationId 06074
value 8.1
created 2025-03-16T13:28:48.073868Z
observed 2025-03-16T13:30:00Z
parameterId temp_dry
stationId 06074
value 8.5
created 2025-03-16T13:18:44.330295Z
observed 2025-03-16T13:20:00Z
parameterId temp_dry
stationId 06074
value 8.7
created 2025-03-16T13:08:46.041361Z
observed 2025-03-16T13:10:00Z
parameterId temp_dry
stationId 06074
value 9.0
created 2025-03-16T12:58:43.289791Z
observed 2025-03-16T13:00:00Z
parameterId temp_dry
stationId 06074
value 9.5
created 2025-03-16T12:48:48.131912Z
observed 2025-03-16T12:50:00Z
parameterId temp_dry
stationId 06074
value 10.3
created 2025-03-16T12:38:42.762439Z
observed 2025-03-16T12:40:00Z
parameterId temp_dry
stationId 06074
value 9.9
created 2025-03-16T12:28:44.530086Z
observed 2025-03-16T12:30:00Z
parameterId temp_dry
stationId 06074
value 8.8
created 2025-03-16T12:18:42.341223Z
observed 2025-03-16T12:20:00Z
parameterId temp_dry
stationId 06074
value 9.9
created 2025-03-16T12:08:48.036191Z
observed 2025-03-16T12:10:00Z
parameterId temp_dry
stationId 06074
value 9.1
created 2025-03-16T11:58:47.740504Z
observed 2025-03-16T12:00:00Z
parameterId temp_dry
stationId 06074
value 9.7
created 2025-03-16T11:48:47.477873Z
observed 2025-03-16T11:50:00Z
parameterId temp_dry
stationId 06074
value 8.9
created 2025-03-16T11:38:43.188797Z
observed 2025-03-16T11:40:00Z
parameterId temp_dry
stationId 06074
value 9.2
created 2025-03-16T11:28:43.926125Z
observed 2025-03-16T11:30:00Z
parameterId temp_dry
stationId 06074
value 8.4
created 2025-03-16T11:18:50.735854Z
observed 2025-03-16T11:20:00Z
parameterId temp_dry
stationId 06074
value 9.7
created 2025-03-16T11:08:46.441920Z
observed 2025-03-16T11:10:00Z
parameterId temp_dry
stationId 06074
value 9.2
created 2025-03-16T10:58:47.097147Z
observed 2025-03-16T11:00:00Z
parameterId temp_dry
stationId 06074
value 8.4
created 2025-03-16T10:48:49.249992Z
observed 2025-03-16T10:50:00Z
parameterId temp_dry
stationId 06074
value 8.6
created 2025-03-16T10:38:46.490052Z
observed 2025-03-16T10:40:00Z
parameterId temp_dry
stationId 06074
value 8.4
created 2025-03-16T10:28:45.261730Z
observed 2025-03-16T10:30:00Z
parameterId temp_dry
stationId 06074
value 8.3
created 2025-03-16T10:18:42.037501Z
observed 2025-03-16T10:20:00Z
parameterId temp_dry
stationId 06074
value 8.1
created 2025-03-16T10:08:43.236009Z
observed 2025-03-16T10:10:00Z
parameterId temp_dry
stationId 06074
value 8.1
created 2025-03-16T09:58:43.916908Z
observed 2025-03-16T10:00:00Z
parameterId temp_dry
stationId 06074
value 7.4
created 2025-03-16T09:48:43.241205Z
observed 2025-03-16T09:50:00Z
parameterId temp_dry
stationId 06074
value 7.2
created 2025-03-16T09:38:44.914330Z
observed 2025-03-16T09:40:00Z
parameterId temp_dry
stationId 06074
value 7.1
created 2025-03-16T09:28:44.746505Z
observed 2025-03-16T09:30:00Z
parameterId temp_dry
stationId 06074
value 6.9
created 2025-03-16T09:18:42.401048Z
observed 2025-03-16T09:20:00Z
parameterId temp_dry
stationId 06074
value 6.9
created 2025-03-16T09:08:47.116019Z
observed 2025-03-16T09:10:00Z
parameterId temp_dry
stationId 06074
value 7.2
created 2025-03-16T08:58:44.308189Z
observed 2025-03-16T09:00:00Z
parameterId temp_dry
stationId 06074
value 7.1
created 2025-03-16T08:48:47.977658Z
observed 2025-03-16T08:50:00Z
parameterId temp_dry
stationId 06074
value 6.9
created 2025-03-16T08:38:42.195574Z
observed 2025-03-16T08:40:00Z
parameterId temp_dry
stationId 06074
value 6.5
created 2025-03-16T08:28:51.033036Z
observed 2025-03-16T08:30:00Z
parameterId temp_dry
stationId 06074
value 6.2
created 2025-03-16T08:18:48.186985Z
observed 2025-03-16T08:20:00Z
parameterId temp_dry
stationId 06074
value 6.1
created 2025-03-16T08:08:47.904621Z
observed 2025-03-16T08:10:00Z
parameterId temp_dry
stationId 06074
value 5.8
created 2025-03-16T07:58:48.536547Z
observed 2025-03-16T08:00:00Z
parameterId temp_dry
stationId 06074
value 5.7
created 2025-03-16T07:48:42.841978Z
observed 2025-03-16T07:50:00Z
parameterId temp_dry
stationId 06074
value 5.2

Now it gets interesting, as we can put the values into a dataframe (more on dataframes later).

In [17]:
import pandas as pd

lst = []

for values in dmi['features']:
    lst.append(pd.DataFrame.from_dict(values['properties'], orient='index').transpose())

In [18]:
df = pd.concat(lst).reset_index()

In [19]:
df

,index,created,observed,parameterId,stationId,value
0,0,2025-03-17T07:38:44.888707Z,2025-03-17T07:40:00Z,temp_dry,06074,0.6
1,0,2025-03-17T07:28:48.151130Z,2025-03-17T07:30:00Z,temp_dry,06074,0.5
2,0,2025-03-17T07:18:41.879446Z,2025-03-17T07:20:00Z,temp_dry,06074,0.2
3,0,2025-03-17T07:08:41.628765Z,2025-03-17T07:10:00Z,temp_dry,06074,-0.2
4,0,2025-03-17T06:58:43.380855Z,2025-03-17T07:00:00Z,temp_dry,06074,-1.7
...,...,...,...,...,...,...
139,0,2025-03-16T08:28:51.033036Z,2025-03-16T08:30:00Z,temp_dry,06074,6.2
140,0,2025-03-16T08:18:48.186985Z,2025-03-16T08:20:00Z,temp_dry,06074,6.1
141,0,2025-03-16T08:08:47.904621Z,2025-03-16T08:10:00Z,temp_dry,06074,5.8
142,0,2025-03-16T07:58:48.536547Z,2025-03-16T08:00:00Z,temp_dry,06074,5.7
143,0,2025-03-16T07:48:42.841978Z,2025-03-16T07:50:00Z,temp_dry,06074,5.2

### HTTP API

An example from Open Data DK 
https://www.opendata.dk/syddjurs-kommune/indeklima-administrationsbygningen-i-hornslet1

In [ ]:
import requests
import pandas as pd

In [20]:
r = requests.get('https://os2iot-backend.prod.os2iot.kmd.dk/api/v1/open-data-dk-sharing/22/data/22')
r.json()

[[{'id': 'indoor-climate-sensor:0c44-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C44'},
   'temperature': {'type': 'Property',
    'value': 19.9,
    'observedAt': '2025-03-17T07:39:08.526Z'},
   'humidity': {'type': 'Property',
    'value': 25,
    'observedAt': '2025-03-17T07:39:08.526Z'},
   'light_level': {'type': 'Property',
    'value': 81,
    'observedAt': '2025-03-17T07:39:08.526Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:39:08.526Z'},
   'co2': {'type': 'Property',
    'value': 571,
    'observedAt': '2025-03-17T07:39:08.526Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316011906, 56.316481751]}}}],
 [{'id': 'indoor-climate-sensor:59d1-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D1'},
   'temperature': {'type': 'Property',
    'value': 22.7,
    'observedAt': '2025-03-17T07:51:31.165Z'},
   'humidity': {'type': 'Property',
    'value': 32,
    'observedAt': '2025-03-17T07:51:31.165Z'},
   'light_level': {'type': 'Property',
    'value': 97,
    'observedAt': '2025-03-17T07:51:31.165Z'},
   'motion': {'type': 'Property',
    'value': 1,
    'observedAt': '2025-03-17T07:51:31.165Z'},
   'co2': {'type': 'Property',
    'value': 1906,
    'observedAt': '2025-03-17T07:51:31.165Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315931439, 56.316594814]}}}],
 [{'id': 'indoor-climate-sensor:59d0-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D0'},
   'temperature': {'type': 'Property',
    'value': 22.9,
    'observedAt': '2025-03-17T07:41:35.913Z'},
   'humidity': {'type': 'Property',
    'value': 27,
    'observedAt': '2025-03-17T07:41:35.913Z'},
   'light_level': {'type': 'Property',
    'value': 355,
    'observedAt': '2025-03-17T07:41:35.913Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:41:35.913Z'},
   'co2': {'type': 'Property',
    'value': 922,
    'observedAt': '2025-03-17T07:41:35.913Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316033363, 56.316465432]}}}],
 [{'id': 'indoor-climate-sensor:59d2-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D2'},
   'temperature': {'type': 'Property',
    'value': 23.6,
    'observedAt': '2025-03-17T07:48:25.061Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:48:25.061Z'},
   'light_level': {'type': 'Property',
    'value': 266,
    'observedAt': '2025-03-17T07:48:25.061Z'},
   'motion': {'type': 'Property',
    'value': 1,
    'observedAt': '2025-03-17T07:48:25.061Z'},
   'co2': {'type': 'Property',
    'value': 811,
    'observedAt': '2025-03-17T07:48:25.061Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316103101, 56.316590319]}}}],
 [{'id': 'indoor-climate-sensor:59d3-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D3'},
   'temperature': {'type': 'Property',
    'value': 20.3,
    'observedAt': '2025-03-17T07:46:29.576Z'},
   'humidity': {'type': 'Property',
    'value': 27,
    'observedAt': '2025-03-17T07:46:29.576Z'},
   'light_level': {'type': 'Property',
    'value': 279,
    'observedAt': '2025-03-17T07:46:29.576Z'},
   'motion': {'type': 'Property',
    'value': 4,
    'observedAt': '2025-03-17T07:46:29.576Z'},
   'co2': {'type': 'Property',
    'value': 781,
    'observedAt': '2025-03-17T07:46:29.576Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316435695, 56.316792582]}}}],
 [{'id': 'indoor-climate-sensor:59d4-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D4'},
   'temperature': {'type': 'Property',
    'value': 19.8,
    'observedAt': '2025-03-17T07:43:36.303Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:43:36.303Z'},
   'light_level': {'type': 'Property',
    'value': 196,
    'observedAt': '2025-03-17T07:43:36.303Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:43:36.303Z'},
   'co2': {'type': 'Property',
    'value': 698,
    'observedAt': '2025-03-17T07:43:36.303Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.31652689, 56.316832693]}}}],
 [{'id': 'indoor-climate-sensor:59d5-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D5'},
   'temperature': {'type': 'Property',
    'value': 21.3,
    'observedAt': '2025-03-17T07:48:09.643Z'},
   'humidity': {'type': 'Property',
    'value': 21,
    'observedAt': '2025-03-17T07:48:09.643Z'},
   'light_level': {'type': 'Property',
    'value': 28,
    'observedAt': '2025-03-17T07:48:09.643Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:48:09.643Z'},
   'co2': {'type': 'Property',
    'value': 475,
    'observedAt': '2025-03-17T07:48:09.643Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315818787, 56.316715168]}}}],
 [{'id': 'indoor-climate-sensor:59d6-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D6'},
   'temperature': {'type': 'Property',
    'value': 19.8,
    'observedAt': '2025-03-17T07:43:31.890Z'},
   'humidity': {'type': 'Property',
    'value': 25,
    'observedAt': '2025-03-17T07:43:31.890Z'},
   'light_level': {'type': 'Property',
    'value': 28,
    'observedAt': '2025-03-17T07:43:31.890Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:43:31.890Z'},
   'co2': {'type': 'Property',
    'value': 525,
    'observedAt': '2025-03-17T07:43:31.890Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316221118, 56.316724085]}}}],
 [{'id': 'indoor-climate-sensor:59d7-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D7'},
   'temperature': {'type': 'Property',
    'value': 20.7,
    'observedAt': '2025-03-17T07:44:09.375Z'},
   'humidity': {'type': 'Property',
    'value': 24,
    'observedAt': '2025-03-17T07:44:09.375Z'},
   'light_level': {'type': 'Property',
    'value': 192,
    'observedAt': '2025-03-17T07:44:09.375Z'},
   'motion': {'type': 'Property',
    'value': 1,
    'observedAt': '2025-03-17T07:44:09.375Z'},
   'co2': {'type': 'Property',
    'value': 604,
    'observedAt': '2025-03-17T07:44:09.375Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315904617, 56.316744109]}}}],
 [{'id': 'indoor-climate-sensor:59d8-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D8'},
   'temperature': {'type': 'Property',
    'value': 22.4,
    'observedAt': '2025-03-17T07:48:46.525Z'},
   'humidity': {'type': 'Property',
    'value': 27,
    'observedAt': '2025-03-17T07:48:46.525Z'},
   'light_level': {'type': 'Property',
    'value': 737,
    'observedAt': '2025-03-17T07:48:46.525Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:48:46.525Z'},
   'co2': {'type': 'Property',
    'value': 500,
    'observedAt': '2025-03-17T07:48:46.525Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315904617, 56.316750051]}}}],
 [{'id': 'indoor-climate-sensor:59d9-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-859D9'},
   'temperature': {'type': 'Property',
    'value': 18.7,
    'observedAt': '2025-03-17T07:45:13.385Z'},
   'humidity': {'type': 'Property',
    'value': 27,
    'observedAt': '2025-03-17T07:45:13.385Z'},
   'light_level': {'type': 'Property',
    'value': 126,
    'observedAt': '2025-03-17T07:45:13.385Z'},
   'motion': {'type': 'Property',
    'value': 8,
    'observedAt': '2025-03-17T07:45:13.385Z'},
   'co2': {'type': 'Property',
    'value': 584,
    'observedAt': '2025-03-17T07:45:13.385Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315711498, 56.316765763]}}}],
 [{'id': 'indoor-climate-sensor:5bce-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BCE'},
   'temperature': {'type': 'Property',
    'value': 22.6,
    'observedAt': '2025-03-17T07:47:38.728Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:47:38.728Z'},
   'light_level': {'type': 'Property',
    'value': 317,
    'observedAt': '2025-03-17T07:47:38.728Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:47:38.728Z'},
   'co2': {'type': 'Property',
    'value': 823,
    'observedAt': '2025-03-17T07:47:38.728Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316162109, 56.31664683]}}}],
 [{'id': 'indoor-climate-sensor:5bcf-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BCF'},
   'temperature': {'type': 'Property',
    'value': 22.5,
    'observedAt': '2025-03-17T07:45:49.734Z'},
   'humidity': {'type': 'Property',
    'value': 27,
    'observedAt': '2025-03-17T07:45:49.734Z'},
   'light_level': {'type': 'Property',
    'value': 400,
    'observedAt': '2025-03-17T07:45:49.734Z'},
   'motion': {'type': 'Property',
    'value': 5,
    'observedAt': '2025-03-17T07:45:49.734Z'},
   'co2': {'type': 'Property',
    'value': 698,
    'observedAt': '2025-03-17T07:45:49.734Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315561295, 56.316715212]}}}],
 [{'id': 'indoor-climate-sensor:5bd0-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD0'},
   'temperature': {'type': 'Property',
    'value': 23,
    'observedAt': '2025-03-17T07:45:29.976Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:45:29.976Z'},
   'light_level': {'type': 'Property',
    'value': 676,
    'observedAt': '2025-03-17T07:45:29.976Z'},
   'motion': {'type': 'Property',
    'value': 4,
    'observedAt': '2025-03-17T07:45:29.976Z'},
   'co2': {'type': 'Property',
    'value': 612,
    'observedAt': '2025-03-17T07:45:29.976Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316022635, 56.316539779]}}}],
 [{'id': 'indoor-climate-sensor:5bd1-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD1'},
   'temperature': {'type': 'Property',
    'value': 23,
    'observedAt': '2025-03-17T07:48:09.434Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:48:09.434Z'},
   'light_level': {'type': 'Property',
    'value': 256,
    'observedAt': '2025-03-17T07:48:09.434Z'},
   'motion': {'type': 'Property',
    'value': 5,
    'observedAt': '2025-03-17T07:48:09.434Z'},
   'co2': {'type': 'Property',
    'value': 641,
    'observedAt': '2025-03-17T07:48:09.434Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316140652, 56.316670609]}}}],
 [{'id': 'indoor-climate-sensor:5bd2-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD2'},
   'temperature': {'type': 'Property',
    'value': 22.7,
    'observedAt': '2025-03-17T07:42:46.603Z'},
   'humidity': {'type': 'Property',
    'value': 20,
    'observedAt': '2025-03-17T07:42:46.603Z'},
   'light_level': {'type': 'Property',
    'value': 308,
    'observedAt': '2025-03-17T07:42:46.603Z'},
   'motion': {'type': 'Property',
    'value': 9,
    'observedAt': '2025-03-17T07:42:46.603Z'},
   'co2': {'type': 'Property',
    'value': 489,
    'observedAt': '2025-03-17T07:42:46.603Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316451788, 56.316733059]}}}],
 [{'id': 'indoor-climate-sensor:5bd3-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD3'},
   'temperature': {'type': 'Property',
    'value': 20.8,
    'observedAt': '2025-03-17T07:48:42.163Z'},
   'humidity': {'type': 'Property',
    'value': 25,
    'observedAt': '2025-03-17T07:48:42.163Z'},
   'light_level': {'type': 'Property',
    'value': 619,
    'observedAt': '2025-03-17T07:48:42.163Z'},
   'motion': {'type': 'Property',
    'value': 43,
    'observedAt': '2025-03-17T07:48:42.163Z'},
   'co2': {'type': 'Property',
    'value': 555,
    'observedAt': '2025-03-17T07:48:42.163Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316408873, 56.316813343]}}}],
 [{'id': 'indoor-climate-sensor:5bd4-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD4'},
   'temperature': {'type': 'Property',
    'value': 23.7,
    'observedAt': '2025-03-17T07:45:32.324Z'},
   'humidity': {'type': 'Property',
    'value': 23,
    'observedAt': '2025-03-17T07:45:32.324Z'},
   'light_level': {'type': 'Property',
    'value': 339,
    'observedAt': '2025-03-17T07:45:32.324Z'},
   'motion': {'type': 'Property',
    'value': 1,
    'observedAt': '2025-03-17T07:45:32.324Z'},
   'co2': {'type': 'Property',
    'value': 612,
    'observedAt': '2025-03-17T07:45:32.324Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316253304, 56.316691452]}}}],
 [{'id': 'indoor-climate-sensor:5bd5-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD5'},
   'temperature': {'type': 'Property',
    'value': 23.5,
    'observedAt': '2025-03-17T07:42:10.043Z'},
   'humidity': {'type': 'Property',
    'value': 24,
    'observedAt': '2025-03-17T07:42:10.043Z'},
   'light_level': {'type': 'Property',
    'value': 1516,
    'observedAt': '2025-03-17T07:42:10.043Z'},
   'motion': {'type': 'Property',
    'value': 4,
    'observedAt': '2025-03-17T07:42:10.043Z'},
   'co2': {'type': 'Property',
    'value': 597,
    'observedAt': '2025-03-17T07:42:10.043Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316033363, 56.316527886]}}}],
 [{'id': 'indoor-climate-sensor:5bd6-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD6'},
   'temperature': {'type': 'Property',
    'value': 22.4,
    'observedAt': '2025-03-17T07:44:13.693Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:44:13.693Z'},
   'light_level': {'type': 'Property',
    'value': 177,
    'observedAt': '2025-03-17T07:44:13.693Z'},
   'motion': {'type': 'Property',
    'value': 1,
    'observedAt': '2025-03-17T07:44:13.693Z'},
   'co2': {'type': 'Property',
    'value': 754,
    'observedAt': '2025-03-17T07:44:13.693Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315947533, 56.316554625]}}}],
 [{'id': 'indoor-climate-sensor:5bd7-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-85BD7'},
   'temperature': {'type': 'Property',
    'value': 22.1,
    'observedAt': '2025-03-17T07:50:13.380Z'},
   'humidity': {'type': 'Property',
    'value': 28,
    'observedAt': '2025-03-17T07:50:13.380Z'},
   'light_level': {'type': 'Property',
    'value': 167,
    'observedAt': '2025-03-17T07:50:13.380Z'},
   'motion': {'type': 'Property',
    'value': 9,
    'observedAt': '2025-03-17T07:50:13.380Z'},
   'co2': {'type': 'Property',
    'value': 764,
    'observedAt': '2025-03-17T07:50:13.380Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315802693, 56.316697383]}}}],
 [{'id': 'indoor-climate-sensor:0c3f-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C3F'},
   'temperature': {'type': 'Property',
    'value': 23.9,
    'observedAt': '2025-03-17T07:47:17.002Z'},
   'humidity': {'type': 'Property',
    'value': 23,
    'observedAt': '2025-03-17T07:47:17.002Z'},
   'light_level': {'type': 'Property',
    'value': 1845,
    'observedAt': '2025-03-17T07:47:17.002Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:47:17.002Z'},
   'co2': {'type': 'Property',
    'value': 729,
    'observedAt': '2025-03-17T07:47:17.002Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316129923, 56.316637888]}}}],
 [{'id': 'indoor-climate-sensor:0c40-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C40'},
   'temperature': {'type': 'Property',
    'value': 22.6,
    'observedAt': '2025-03-17T07:46:17.844Z'},
   'humidity': {'type': 'Property',
    'value': 28,
    'observedAt': '2025-03-17T07:46:17.844Z'},
   'light_level': {'type': 'Property',
    'value': 199,
    'observedAt': '2025-03-17T07:46:17.844Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:46:17.844Z'},
   'co2': {'type': 'Property',
    'value': 961,
    'observedAt': '2025-03-17T07:46:17.844Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315893888, 56.316673581]}}}],
 [{'id': 'indoor-climate-sensor:0c41-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C41'},
   'temperature': {'type': 'Property',
    'value': 23.8,
    'observedAt': '2025-03-17T07:48:49.283Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:48:49.283Z'},
   'light_level': {'type': 'Property',
    'value': 1468,
    'observedAt': '2025-03-17T07:48:49.283Z'},
   'motion': {'type': 'Property',
    'value': 4,
    'observedAt': '2025-03-17T07:48:49.283Z'},
   'co2': {'type': 'Property',
    'value': 932,
    'observedAt': '2025-03-17T07:48:49.283Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.315926075, 56.316584387]}}}],
 [{'id': 'indoor-climate-sensor:0c42-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C42'},
   'temperature': {'type': 'Property',
    'value': 21.4,
    'observedAt': '2025-03-17T07:43:01.588Z'},
   'humidity': {'type': 'Property',
    'value': 26,
    'observedAt': '2025-03-17T07:43:01.588Z'},
   'light_level': {'type': 'Property',
    'value': 87,
    'observedAt': '2025-03-17T07:43:01.588Z'},
   'motion': {'type': 'Property',
    'value': 5,
    'observedAt': '2025-03-17T07:43:01.588Z'},
   'co2': {'type': 'Property',
    'value': 540,
    'observedAt': '2025-03-17T07:43:01.588Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316001177, 56.316715215]}}}],
 [{'id': 'indoor-climate-sensor:0c43-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C43'},
   'temperature': {'type': 'Property',
    'value': 20.6,
    'observedAt': '2025-03-17T07:49:51.020Z'},
   'humidity': {'type': 'Property',
    'value': 23,
    'observedAt': '2025-03-17T07:49:51.020Z'},
   'light_level': {'type': 'Property',
    'value': 30,
    'observedAt': '2025-03-17T07:49:51.020Z'},
   'motion': {'type': 'Property',
    'value': 0,
    'observedAt': '2025-03-17T07:49:51.020Z'},
   'co2': {'type': 'Property',
    'value': 573,
    'observedAt': '2025-03-17T07:49:51.020Z'},
   'location': {'type': 'GeoProperty',
    'value': {'type': 'Point', 'coordinates': [10.316183567, 56.316750922]}}}],
 [{'id': 'indoor-climate-sensor:0c45-Elsys',
   'type': 'indoor-climate-sensor',
   'name': {'type': 'Property', 'value': 'ERS2-CO2-C0C45'},
   'temperature': {'type': 'Property',

In [21]:
schema = r.json()[0][0].keys()
df = pd.DataFrame(columns=schema)
df['time'] = []

for t in r.json():
    for i in t:
        df.loc[len(df.index)] = [
            i['id'], 
            i['type'], 
            i['name']['value'], 
            i['temperature']['value'], 
            i['humidity']['value'],  
            i['light_level']['value'],  
            i['motion']['value'], 
            i['co2']['value'],  
            i['location']['value']['coordinates'],
            i['temperature']['observedAt'],
        ]

In [22]:
df

,id,type,name,temperature,humidity,light_level,motion,co2,location,time
0,indoor-climate-sensor:0c44-Elsys,indoor-climate-sensor,ERS2-CO2-C0C44,19.9,25,81,0,571,"[10.316011906, 56.316481751]",2025-03-17T07:39:08.526Z
1,indoor-climate-sensor:59d1-Elsys,indoor-climate-sensor,ERS2-CO2-859D1,22.7,32,97,1,1906,"[10.315931439, 56.316594814]",2025-03-17T07:51:31.165Z
2,indoor-climate-sensor:59d0-Elsys,indoor-climate-sensor,ERS2-CO2-859D0,22.9,27,355,0,922,"[10.316033363, 56.316465432]",2025-03-17T07:41:35.913Z
3,indoor-climate-sensor:59d2-Elsys,indoor-climate-sensor,ERS2-CO2-859D2,23.6,26,266,1,811,"[10.316103101, 56.316590319]",2025-03-17T07:48:25.061Z
4,indoor-climate-sensor:59d3-Elsys,indoor-climate-sensor,ERS2-CO2-859D3,20.3,27,279,4,781,"[10.316435695, 56.316792582]",2025-03-17T07:46:29.576Z
5,indoor-climate-sensor:59d4-Elsys,indoor-climate-sensor,ERS2-CO2-859D4,19.8,26,196,0,698,"[10.31652689, 56.316832693]",2025-03-17T07:43:36.303Z
6,indoor-climate-sensor:59d5-Elsys,indoor-climate-sensor,ERS2-CO2-859D5,21.3,21,28,0,475,"[10.315818787, 56.316715168]",2025-03-17T07:48:09.643Z
7,indoor-climate-sensor:59d6-Elsys,indoor-climate-sensor,ERS2-CO2-859D6,19.8,25,28,0,525,"[10.316221118, 56.316724085]",2025-03-17T07:43:31.890Z
8,indoor-climate-sensor:59d7-Elsys,indoor-climate-sensor,ERS2-CO2-859D7,20.7,24,192,1,604,"[10.315904617, 56.316744109]",2025-03-17T07:44:09.375Z
9,indoor-climate-sensor:59d8-Elsys,indoor-climate-sensor,ERS2-CO2-859D8,22.4,27,737,0,500,"[10.315904617, 56.316750051]",2025-03-17T07:48:46.525Z
10,indoor-climate-sensor:59d9-Elsys,indoor-climate-sensor,ERS2-CO2-859D9,18.7,27,126,8,584,"[10.315711498, 56.316765763]",2025-03-17T07:45:13.385Z
11,indoor-climate-sensor:5bce-Elsys,indoor-climate-sensor,ERS2-CO2-85BCE,22.6,26,317,0,823,"[10.316162109, 56.31664683]",2025-03-17T07:47:38.728Z
12,indoor-climate-sensor:5bcf-Elsys,indoor-climate-sensor,ERS2-CO2-85BCF,22.5,27,400,5,698,"[10.315561295, 56.316715212]",2025-03-17T07:45:49.734Z
13,indoor-climate-sensor:5bd0-Elsys,indoor-climate-sensor,ERS2-CO2-85BD0,23.0,26,676,4,612,"[10.316022635, 56.316539779]",2025-03-17T07:45:29.976Z
14,indoor-climate-sensor:5bd1-Elsys,indoor-climate-sensor,ERS2-CO2-85BD1,23.0,26,256,5,641,"[10.316140652, 56.316670609]",2025-03-17T07:48:09.434Z
15,indoor-climate-sensor:5bd2-Elsys,indoor-climate-sensor,ERS2-CO2-85BD2,22.7,20,308,9,489,"[10.316451788, 56.316733059]",2025-03-17T07:42:46.603Z
16,indoor-climate-sensor:5bd3-Elsys,indoor-climate-sensor,ERS2-CO2-85BD3,20.8,25,619,43,555,"[10.316408873, 56.316813343]",2025-03-17T07:48:42.163Z
17,indoor-climate-sensor:5bd4-Elsys,indoor-climate-sensor,ERS2-CO2-85BD4,23.7,23,339,1,612,"[10.316253304, 56.316691452]",2025-03-17T07:45:32.324Z
18,indoor-climate-sensor:5bd5-Elsys,indoor-climate-sensor,ERS2-CO2-85BD5,23.5,24,1516,4,597,"[10.316033363, 56.316527886]",2025-03-17T07:42:10.043Z
19,indoor-climate-sensor:5bd6-Elsys,indoor-climate-sensor,ERS2-CO2-85BD6,22.4,26,177,1,754,"[10.315947533, 56.316554625]",2025-03-17T07:44:13.693Z
20,indoor-climate-sensor:5bd7-Elsys,indoor-climate-sensor,ERS2-CO2-85BD7,22.1,28,167,9,764,"[10.315802693, 56.316697383]",2025-03-17T07:50:13.380Z
21,indoor-climate-sensor:0c3f-Elsys,indoor-climate-sensor,ERS2-CO2-C0C3F,23.9,23,1845,0,729,"[10.316129923, 56.316637888]",2025-03-17T07:47:17.002Z
22,indoor-climate-sensor:0c40-Elsys,indoor-climate-sensor,ERS2-CO2-C0C40,22.6,28,199,0,961,"[10.315893888, 56.316673581]",2025-03-17T07:46:17.844Z
23,indoor-climate-sensor:0c41-Elsys,indoor-climate-sensor,ERS2-CO2-C0C41,23.8,26,1468,4,932,"[10.315926075, 56.316584387]",2025-03-17T07:48:49.283Z
24,indoor-climate-sensor:0c42-Elsys,indoor-climate-sensor,ERS2-CO2-C0C42,21.4,26,87,5,540,"[10.316001177, 56.316715215]",2025-03-17T07:43:01.588Z
25,indoor-climate-sensor:0c43-Elsys,indoor-climate-sensor,ERS2-CO2-C0C43,20.6,23,30,0,573,"[10.316183567, 56.316750922]",2025-03-17T07:49:51.020Z
26,indoor-climate-sensor:0c45-Elsys,indoor-climate-sensor,ERS2-CO2-C0C45,20.2,24,106,0,582,"[10.31588316, 56.316697385]",2025-03-17T07:47:30.395Z
27,indoor-climate-sensor:0c46-Elsys,indoor-climate-sensor,ERS2-CO2-C0C46,19.3,28,253,2,621,"[10.315947533, 56.316683576]",2025-03-17T07:51:00.885Z
28,indoor-climate-sensor:0c47-Elsys,indoor-climate-sensor,ERS2-CO2-C0C47,20.7,23,0,0,513,"[10.315888524, 56.316718206]",2025-03-17T07:42:44.961Z
29,indoor-climate-sensor:0c48-Elsys,indoor-climate-sensor,ERS2-CO2-C0C48,22.2,27,47,0,856,"[10.315888524, 56.316709278]",2025-03-17T07:47:06.538Z
30,indoor-climate-sensor:0d89-Elsys,indoor-climate-sensor,ERS2-CO2-C0D89,21.8,25,118,5,590,"[10.315974355, 56.316727131]",2025-03-17T07:47:22.039Z
31,indoor-climate-sensor:0d8a-Elsys,indoor-climate-sensor,ERS2-CO2-C0D8A,21.8,25,2067,0,555,"[10.315582752, 56.31673604]",2025-03-17T07:45:24.347Z
32,indoor-climate-sensor:0d8b-Elsys,indoor-climate-sensor,ERS2-CO2-C0D8B,21.9,25,2044,12,568,"[10.315647125, 56.316852024]",2025-03-17T07:48:43.923Z
33,indoor-climate-sensor:0d8c-Elsys,indoor-climate-sensor,ERS2-CO2-C0D8C,22.8,24,388,5,683,"[10.315754414, 56.316709278]",2025-03-17T07:47:41.173Z
34,indoor-climate-sensor:0d8d-Elsys,indoor-climate-sensor,ERS2-CO2-C0D8D,22.4,26,970,8,798,"[10.315926075, 56.316512994]",2025-03-17T07:48:35.228Z
35,indoor-climate-sensor:0d8e-Elsys,indoor-climate-sensor,ERS2-CO2-C0D8E,23.5,23,2953,3,629,"[10.315995812, 56.316501111]",2025-03-17T07:44:36.783Z
36,indoor-climate-sensor:0d8f-Elsys,indoor-climate-sensor,ERS2-CO2-C0D8F,23.4,23,869,1,662,"[10.316301584, 56.316709242]",2025-03-17T07:50:07.180Z
37,indoor-climate-sensor:0d90-Elsys,indoor-climate-sensor,ERS2-CO2-C0D90,21.9,28,1575,2,673,"[10.315609574, 56.316798463]",2025-03-17T07:47:34.088Z
38,indoor-climate-sensor:0d91-Elsys,indoor-climate-sensor,ERS2-CO2-C0D91,21.9,25,984,4,594,"[10.316301584, 56.316762803]",2025-03-17T07:42:53.496Z
39,indoor-climate-sensor:0d92-Elsys,indoor-climate-sensor,ERS2-CO2-C0D92,21.7,25,123,0,603,"[10.316087008, 56.316695861]",2025-03-17T07:46:20.043Z

An example from Open Data DK 
https://www.opendata.dk/city-of-aarhus/transaktionsdata-fra-aarhus-kommunes-biblioteker

In [23]:
url = 'https://admin.opendata.dk/api/3/action/datastore_search?resource_id=5b9b00f9-543e-4ac0-994c-dbbc8b38e7e5'
r = requests.get(url)
r.json()

{'help': 'https://admin.opendata.dk/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'include_total': True,
  'resource_id': '5b9b00f9-543e-4ac0-994c-dbbc8b38e7e5',
  'fields': [{'type': 'int', 'id': '_id'},
   {'type': 'int4', 'id': 'id'},
   {'type': 'timestamp', 'id': 'time'},
   {'type': 'int4', 'id': 'min5'},
   {'type': 'int4', 'id': 'min60'},
   {'type': 'int4', 'id': 'min1440'},
   {'type': 'int4', 'id': 'today'}],
  'records_format': 'objects',
  'records': [{'_id': 1,
    'id': 3,
    'time': '2025-03-17T08:50:04',
    'min5': 12,
    'min60': 211,
    'min1440': 709,
    'today': 273},
   {'_id': 2,
    'id': 4,
    'time': '2025-03-17T08:50:04',
    'min5': 30,
    'min60': 312,
    'min1440': 971,
    'today': 373},
   {'_id': 3,
    'id': 5,
    'time': '2025-03-17T08:50:04',
    'min5': 0,
    'min60': 0,
    'min1440': 50,
    'today': 1},
   {'_id': 4,
    'id': 6,
    'time': '2025-03-17T08:50:04',
    'min5': 0,
    'min60': 2,
    'min1440': 167,
    'today': 4},
   {'_id': 5,
    'id': 7,
    'time': '2025-03-17T08:50:04',
    'min5': 0,
    'min60': 27,
    'min1440': 663,
    'today': 27},
   {'_id': 6,
    'id': 8,
    'time': '2025-03-17T08:50:04',
    'min5': 0,
    'min60': 25,
    'min1440': 26,
    'today': 26},
   {'_id': 7,
    'id': 9,
    'time': '2025-03-17T08:50:04',
    'min5': 0,
    'min60': 20,
    'min1440': 71,
    'today': 20}],
  '_links': {'start': '/api/3/action/datastore_search?resource_id=5b9b00f9-543e-4ac0-994c-dbbc8b38e7e5',
   'next': '/api/3/action/datastore_search?offset=100&resource_id=5b9b00f9-543e-4ac0-994c-dbbc8b38e7e5'},
  'total': 7}}

In [24]:
# Using sql in query for filtering
sql_url = 'https://admin.opendata.dk/api/3/action/datastore_search_sql?sql=SELECT * from "5b9b00f9-543e-4ac0-994c-dbbc8b38e7e5" WHERE id=3'
r = requests.get(sql_url)
r.json()

{'help': 'https://admin.opendata.dk/api/3/action/help_show?name=datastore_search_sql',
 'success': True,
 'result': {'records': [{'min1440': 709,
    '_id': 1,
    '_full_text': "'-03':7 '-17':8 '04':11 '12':1 '2025':6 '211':3 '273':5 '3':4 '50':10 '709':2 't08':9",
    'id': 3,
    'time': '2025-03-17T08:50:04',
    'min60': 211,
    'min5': 12,
    'today': 273}],
  'fields': [{'type': 'int4', 'id': '_id'},
   {'type': 'tsvector', 'id': '_full_text'},
   {'type': 'int4', 'id': 'id'},
   {'type': 'timestamp', 'id': 'time'},
   {'type': 'int4', 'id': 'min5'},
   {'type': 'int4', 'id': 'min60'},
   {'type': 'int4', 'id': 'min1440'},
   {'type': 'int4', 'id': 'today'}],
  'sql': 'SELECT * from "5b9b00f9-543e-4ac0-994c-dbbc8b38e7e5" WHERE id=3'}}

## API Best Practices

Working with APIs requires careful handling of errors, timeouts, and security. Here are essential best practices.

### Error Handling

Always handle potential errors when working with APIs. Network issues, server errors, and invalid responses can occur.

In [ ]:
import requests
import time

def fetch_data_safe(url, params=None, max_retries=3):
    """
    Safely fetch data from an API with error handling and retries.
    
    Args:
        url: API endpoint URL
        params: Optional parameters
        max_retries: Maximum number of retry attempts
        
    Returns:
        JSON response or None if all attempts fail
    """
    for attempt in range(max_retries):
        try:
            # Set timeout to prevent hanging
            response = requests.get(url, params=params, timeout=10)
            
            # Check if request was successful
            response.raise_for_status()  # Raises HTTPError for bad status codes
            
            return response.json()
            
        except requests.exceptions.Timeout:
            print(f'Timeout on attempt {attempt + 1}/{max_retries}')
            
        except requests.exceptions.ConnectionError:
            print(f'Connection error on attempt {attempt + 1}/{max_retries}')
            
        except requests.exceptions.HTTPError as e:
            print(f'HTTP error: {e}')
            if response.status_code == 404:
                print('Resource not found')
                return None
            elif response.status_code >= 500:
                print('Server error, retrying...')
            else:
                return None
                
        except requests.exceptions.JSONDecodeError:
            print('Invalid JSON response')
            return None
            
        except Exception as e:
            print(f'Unexpected error: {e}')
            return None
        
        # Wait before retrying
        if attempt < max_retries - 1:
            wait_time = 2 ** attempt  # Exponential backoff
            print(f'Waiting {wait_time} seconds before retry...')
            time.sleep(wait_time)
    
    print('All retry attempts failed')
    return None

# Example usage
# data = fetch_data_safe('https://api.example.com/data')

### Secure API Key Management

**Never** hard-code API keys in your notebooks or commit them to version control!

In [ ]:
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ✅ GOOD: Read API key from environment variable
api_key = os.getenv('API_KEY')

# Alternative: Read from .env file manually
def load_env_file(filepath='.env'):
    """Load environment variables from .env file."""
    env_vars = {}
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    except FileNotFoundError:
        print(f'Warning: {filepath} not found!')
    return env_vars

# Usage
# env_vars = load_env_file()
# api_key = env_vars.get('API_KEY')

### Rate Limiting

Many APIs have rate limits. Respect them to avoid being blocked!

In [ ]:
import time
from datetime import datetime

class RateLimiter:
    """Simple rate limiter for API calls."""
    
    def __init__(self, calls_per_minute=60):
        self.calls_per_minute = calls_per_minute
        self.min_interval = 60.0 / calls_per_minute
        self.last_call = None
    
    def wait_if_needed(self):
        """Wait if necessary to respect rate limit."""
        if self.last_call is not None:
            elapsed = time.time() - self.last_call
            if elapsed < self.min_interval:
                wait_time = self.min_interval - elapsed
                print(f'Rate limiting: waiting {wait_time:.2f} seconds...')
                time.sleep(wait_time)
        
        self.last_call = time.time()

# Example usage
limiter = RateLimiter(calls_per_minute=30)  # Max 30 calls per minute

def fetch_with_rate_limit(url):
    """Fetch data while respecting rate limits."""
    limiter.wait_if_needed()
    response = requests.get(url, timeout=10)
    return response.json()

# Make multiple requests
# for i in range(5):
#     data = fetch_with_rate_limit(f'https://api.example.com/item/{i}')
#     print(f'Fetched item {i}')

### Setting Timeouts

Always set timeouts to prevent your program from hanging indefinitely.

In [ ]:
# ✅ GOOD: With timeout
try:
    response = requests.get('https://api.example.com/data', timeout=10)
except requests.exceptions.Timeout:
    print('Request timed out after 10 seconds')

# ❌ BAD: No timeout (can hang forever)
# response = requests.get('https://api.example.com/data')

# You can also set separate connect and read timeouts
# response = requests.get(url, timeout=(3, 10))  # 3s connect, 10s read

### Checking Response Status

Always verify the response was successful before processing.

In [ ]:
def check_response_status(response):
    """Check and handle different HTTP status codes."""
    
    if response.status_code == 200:
        print('✓ Success')
        return True
        
    elif response.status_code == 400:
        print('✗ Bad Request - check your parameters')
        
    elif response.status_code == 401:
        print('✗ Unauthorized - check your API key')
        
    elif response.status_code == 403:
        print('✗ Forbidden - you don\'t have permission')
        
    elif response.status_code == 404:
        print('✗ Not Found - endpoint doesn\'t exist')
        
    elif response.status_code == 429:
        print('✗ Too Many Requests - you\'re being rate limited')
        
    elif response.status_code >= 500:
        print('✗ Server Error - try again later')
        
    else:
        print(f'✗ Unexpected status code: {response.status_code}')
    
    return False

# Example
# response = requests.get('https://api.example.com/data')
# if check_response_status(response):
#     data = response.json()

### Complete Example: Robust API Call

In [ ]:
import requests
import time
import os
from typing import Optional, Dict, Any

def make_api_call(
    url: str,
    params: Optional[Dict[str, Any]] = None,
    headers: Optional[Dict[str, str]] = None,
    timeout: int = 10,
    max_retries: int = 3
) -> Optional[Dict]:
    """
    Make a robust API call with best practices.
    
    Args:
        url: API endpoint URL
        params: Query parameters
        headers: HTTP headers (including auth)
        timeout: Request timeout in seconds
        max_retries: Maximum retry attempts
        
    Returns:
        JSON response or None if failed
    """
    
    for attempt in range(max_retries):
        try:
            response = requests.get(
                url,
                params=params,
                headers=headers,
                timeout=timeout
            )
            
            # Check status
            if response.status_code == 200:
                return response.json()
                
            elif response.status_code == 429:
                # Rate limited - wait longer
                wait_time = int(response.headers.get('Retry-After', 60))
                print(f'Rate limited. Waiting {wait_time}s...')
                time.sleep(wait_time)
                continue
                
            elif response.status_code >= 500:
                # Server error - retry with backoff
                wait_time = 2 ** attempt
                print(f'Server error. Retrying in {wait_time}s...')
                time.sleep(wait_time)
                continue
                
            else:
                # Client error - don't retry
                print(f'Request failed: {response.status_code}')
                print(response.text)
                return None
                
        except requests.exceptions.Timeout:
            print(f'Timeout on attempt {attempt + 1}')
            
        except requests.exceptions.RequestException as e:
            print(f'Request error: {e}')
            
        if attempt < max_retries - 1:
            time.sleep(1)
    
    return None

# Example usage
# api_key = os.getenv('API_KEY')
# headers = {'Authorization': f'Bearer {api_key}'}
# data = make_api_call(
#     'https://api.example.com/data',
#     params={'limit': 100},
#     headers=headers
# )

### Summary of Best Practices

1. **Always handle errors** with try-except blocks
2. **Set timeouts** to prevent hanging
3. **Store API keys securely** in environment variables
4. **Respect rate limits** and implement backoff strategies
5. **Check response status** before processing data
6. **Implement retry logic** for transient errors
7. **Log errors** for debugging
8. **Use sessions** for multiple requests to the same host
9. **Validate responses** before using the data
10. **Document your API interactions** for other developers

return to [overview](../00_overview.ipynb)